language: python

sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"

matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"

install:
  - pip install --upgrade pytest
  - pip install --editable .

script:
  - pytest

notifications:
  email: false
